import baseConfig from '../../eslint.config.mjs';

export default [
  ...baseConfig,
  {
    // Generated by `wrangler types` (the cf-typegen target).
    ignores: ['env.d.ts'],
  },
  {
    files: ['**/*.ts'],
    rules: {
      // The Agents SDK runs SQL as a tagged template (`this.sql\`...\``), and
      // a write is a statement whose result is intentionally unused.
      '@typescript-eslint/no-unused-expressions': ['error', { allowTaggedTemplates: true }],
    },
  },
];
